# Generated by Django 4.2.7 on 2023-11-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Введите названия сайта')),
                ('logo', models.ImageField(upload_to='image_user/', verbose_name='Загрузите логотип')),
                ('description', models.TextField(verbose_name='Введите описание сайта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефонный номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Введите свою почту')),
            ],
        ),
    ]
