# Generated by Django 4.2.7 on 2023-11-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': '', 'verbose_name_plural': 'Настройки'},
        ),
    ]
